name: Latest Medium Posts
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@gimansabandara2001"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          # These extra settings help force the connection
          readme_path: "./README.md"
          max_post_count: 5
          template: "$newline- [$title]($url)"
